### ISSUE TITLE
Adding Toasts instead of Alerts

### ISSUE THREAD

**Issue by tend2infinity** [Namanl2001/MERN-Gurujii-dev#152]
**Describe the bug**
Whenever we add, delete or update a user we get an alert. I want to show Toasts on the frontend instead of alerts for a better UI experience.

**Comment by Namanl2001** [comment]
That's a nice option but we want to reload the site automatically when any of the above mentioned actions is performed. And currently when we clock the OK hutton of the alert it reloads the page so that new data could be fetched from backend. E.g. if a post req is made with status code 200 but still the new data will not be rendered on frontend until we reload the webpage.
So is realoading possible with toast msgs?

**Comment by tend2infinity** [comment]
I was thinking to show a toast after reloading the page, but I guess it won't make much sense. Nevertheless toast messages are useful when the DOM gets updated without reloading. So I can drop this issue
