### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by sagar-barapatre** [Namanl2001/MERN-Gurujii-dev#17]
We can improve the UI of the README.md so that setting up the project can be much more easy and will get more details about the project with a better UI

**Comment by nikitakapoor1919** [comment]
Can I work on this issue @sagar-barapatre .Please assign this task to me.

**Comment by sagar-barapatre** [comment]
Hey @nikitakapoor1919 can you please propose the idea of how exactly the README.md file should look like.
As in have you decided something

**Comment by nikitakapoor1919** [comment]
I am attaching this screenshot of changes i have made in my local.
Should i add Technology Stack ?
![image](https://user-images.githubusercontent.com/62166533/110460956-de024b80-80f4-11eb-9cdd-84b15e1e8105.png)

And below i have add button so that we can navigate to live website
![image](https://user-images.githubusercontent.com/62166533/110461685-c6779280-80f5-11eb-87a8-4ff63d022dc3.png)

What do u think about this @sagar-barapatre  ?

**Comment by sagar-barapatre** [comment]
Yeah I think tech stack would be important. What say @Namanl2001 ? This readme really looks cool...
Keep working and let me know if you need some help

**Comment by Navya-amarneni** [comment]
Hey!!! I found this issue to be interesting. Can you assign me this issue? I would like to propose my changes.

**Comment by sagar-barapatre** [comment]
Hi @Navya-amarneni the PR has already been made, so if you want to contribute on this you can suggest some changes while reviewing the PR #25

**Comment by Samridhi-98** [comment]
@Namanl2001 I would like to suggest some changes in the README file like the top image is too large and false the spacing between different sections should be a little less that will make the README more precise and appealing.

**Comment by Namanl2001** [comment]
Yes @Samridhi-98 i's feeling the same. Also we also need to add a link to contributing.md in it so it would be nice to make a new pr. go ahead

**Comment by Samridhi-98** [comment]
@Namanl2001 Sure, I will make the required changes and make new PR also.
