### ISSUE TITLE
New UI for the Cards

### ISSUE THREAD

**Issue by AmeyaJain-25** [Namanl2001/MERN-Gurujii-dev#27]
I would like to give a new UI for the Cards with some background, some animation and an attractive card
Please assign this to me under GSSoC 21'

**Comment by Namanl2001** [comment]
Thanks @AmeyaJain-25

**Comment by sagar-barapatre** [comment]
Before making a PR please give us an idea as in what the card will look like after applying animations and all those things.

**Comment by AmeyaJain-25** [comment]
Yes sure,
I'll make the UI for the card and will give you a preview before making PR

**Comment by tanwi1234** [comment]
I would like to give a new UI for the Cards with some background, some animation and an attractive card
Please assign this to me under GSSoC 21'

Something like this where we store data and display it on mentors page so that student show the availables teachers and easily contacts  them.



![Screenshot (1067)](https://user-images.githubusercontent.com/65597267/110763651-226a2480-8278-11eb-9f6c-66f9f47e12eb.png)
![Screenshot (1068)](https://user-images.githubusercontent.com/65597267/110763669-25651500-8278-11eb-81da-b1528e240407.png)
![Screenshot (1069)](https://user-images.githubusercontent.com/65597267/110763693-2bf38c80-8278-11eb-9242-46ae556419d4.png)
![Screenshot (1070)](https://user-images.githubusercontent.com/65597267/110763711-2eee7d00-8278-11eb-8e1b-5e2cbfc237bb.png)
![Screenshot (1071)](https://user-images.githubusercontent.com/65597267/110763719-3150d700-8278-11eb-8599-19242407241f.png)

**Comment by AmeyaJain-25** [comment]
@Namanl2001 Please assign this issue to @tanwi1234 as I'm having issues with setting up the project

**Comment by Namanl2001** [comment]
@AmeyaJain-25 feel free to clear your doubts here itself.

**Comment by AmeyaJain-25** [comment]
I'm not able to run the backend. Hence cannot see the cards

**Comment by Namanl2001** [comment]
pull the latest changes and follow readme.md

**Comment by khushi935** [comment]
Can I work on this?

**Comment by Namanl2001** [comment]
@khushi935 are you working on this issue?

**Comment by ChitvanRamani22** [comment]
@Namanl2001 could you please assign this issue to me.

**Comment by ChitvanRamani22** [comment]
@Namanl2001 i have created a pull request through a branch named newcards.
Please do check it.

**Comment by sagar-barapatre** [comment]
The PR #113  for this already been made so I am closing this issue.

**Comment by ChitvanRamani22** [comment]
@sagar-barapatre could you please view my changes once if you like them more you can merge it as i got assigned i worked on it for 2 days atleast have a look once.

**Comment by Namanl2001** [comment]
closing via #142
